// Pseudocode strings for each algorithm.
// Line indices are used by PseudocodePanel's activeLine prop.

export const PSEUDOCODE: Record<string, string[]> = {
  bfs: [
    'function BFS(problem):',
    '  node ← Node(problem.initialState)',
    '  if problem.isGoal(node.state): return node',
    '  frontier ← Queue([node])',
    '  explored ← {}',
    '  loop:',
    '    if isEmpty(frontier): return failure',
    '    node ← frontier.dequeue()',
    '    explored.add(node.state)',
    '    for action in problem.actions(node.state):',
    '      child ← childNode(problem, node, action)',
    '      if child.state ∉ explored ∪ frontier:',
    '        if problem.isGoal(child.state): return child',
    '        frontier.enqueue(child)',
  ],

  dfs: [
    'function DFS(problem):',
    '  frontier ← Stack([Node(problem.initialState)])',
    '  explored ← {}',
    '  loop:',
    '    if isEmpty(frontier): return failure',
    '    node ← frontier.pop()',
    '    if problem.isGoal(node.state): return node',
    '    explored.add(node.state)',
    '    for action in problem.actions(node.state):',
    '      child ← childNode(problem, node, action)',
    '      if child.state ∉ explored ∪ frontier:',
    '        frontier.push(child)',
  ],

  dls: [
    'function DLS(problem, limit):',
    '  return recursiveDLS(Node(problem.initialState), problem, limit)',
    '',
    'function recursiveDLS(node, problem, limit):',
    '  if problem.isGoal(node.state): return node',
    '  if limit == 0: return cutoff',
    '  cutoffOccurred ← false',
    '  for action in problem.actions(node.state):',
    '    child ← childNode(problem, node, action)',
    '    result ← recursiveDLS(child, problem, limit - 1)',
    '    if result == cutoff: cutoffOccurred ← true',
    '    else if result ≠ failure: return result',
    '  if cutoffOccurred: return cutoff',
    '  else: return failure',
  ],

  iddfs: [
    'function IDDFS(problem):',
    '  for depth = 0 to ∞:',
    '    result ← DLS(problem, depth)',
    '    if result ≠ cutoff: return result',
  ],

  ucs: [
    'function UNIFORM-COST-SEARCH(problem):',
    '  node ← Node(problem.initialState, path_cost=0)',
    '  frontier ← priority queue ordered by path_cost',
    '  frontier.add(node)',
    '  reached ← {problem.initialState: 0}',
    '  while frontier is not empty:',
    '    node ← POP(frontier)  // lowest path_cost',
    '    if problem.isGoal(node.state): return node',
    '    for each child in EXPAND(problem, node):',
    '      s ← child.state',
    '      new_cost ← node.path_cost + step_cost',
    '      if s not in reached or new_cost < reached[s]:',
    '        reached[s] ← new_cost',
    '        frontier.push(child, new_cost)',
    '  return failure',
  ],

  'bidirectional-bfs': [
    'function BIDIRECTIONAL-BFS(problem):',
    '  frontierF ← Queue([start])',
    '  frontierB ← Queue([goal])',
    '  parentF[start] ← null',
    '  parentB[goal] ← null',
    '  while frontierF and frontierB are not empty:',
    '    meet ← expandOneLayer(frontierF, parentF, parentB)',
    '    if meet ≠ null: return buildPath(meet, parentF, parentB)',
    '    meet ← expandOneLayer(frontierB, parentB, parentF)',
    '    if meet ≠ null: return buildPath(meet, parentF, parentB)',
    '  return failure',
  ],
};
